Chapter06/azure/BookApp/BookApp.Web.V2/Controllers/BookReviewsController.cs
using Microsoft.AspNetCore.Mvc;
using BookApp.DAL;
using BookApp.Models;
using System.Reflection.Metadata.Ecma335;
using System.Net.Http;
using BookApp.Web.Models;
using System.Threading.Tasks;
using System;

namespace BookApp.Web.V2.Controllers
{
    public class BookReviewsController : Controller
    {
        private IBookRepository bookRepository;
        private SentimentAnalysisServiceSettings sentimentAnalysisServiceSettings;

        public BookReviewsController(IBookRepository bookRepository, SentimentAnalysisServiceSettings sentimentAnalysisServiceSettings)
        {
            this.bookRepository = bookRepository;
            this.sentimentAnalysisServiceSettings = sentimentAnalysisServiceSettings;
        }

        // GET: BookReviews
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            var book = bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }


        // GET: BookReviews/Create
        public ActionResult Create(int bookId)
        {
            var book = bookRepository.GetBookById(bookId);
            return View(new BookReview { Book = book });
        }

        // POST: BookReviews/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int bookId,[Bind("Rating,Review,Title")] BookReview bookReview)
        {

            if (ModelState.IsValid)
            {
                bookRepository.AddReviewToBook(bookId, bookReview);
                return RedirectToAction("Index",new { id = bookId});
            }
            var book = bookRepository.GetBookById(bookId);
            bookReview.Book = book;
            return View(bookReview);


        }

        // GET: BookReviews/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            BookReview bookReview = bookRepository.GetBookReviewById(id);
            if (bookReview == null)
            {
                return NotFound();
            }
            return View(bookReview);
        }

        // POST: BookReviews/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int bookId,[Bind( "Id,Rating,Review,Title")] BookReview bookReview)
        {
            if (ModelState.IsValid)
            {
                bookRepository.UpdateBookReview(bookReview);
                return RedirectToAction("Index", new { id = bookId });
            }
            return View(bookReview);
        }

        // GET: BookReviews/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            BookReview bookReview = bookRepository.GetBookReviewById(id);
            if (bookReview == null)
            {
                return NotFound();
            }
            return View(bookReview);
        }

        // POST: BookReviews/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id,int bookId)
        {
            bookRepository.DeleteBookReview(id);
            return RedirectToAction("Index", new { id = bookId });
        }

        [HttpGet]
        [Route("GetSentiment")]
        public async Task<int> GetSentiment(string text)
        {
            HttpClient _client = new HttpClient();
            HttpRequestMessage sentimentRequest = new HttpRequestMessage(HttpMethod.Get, $"{sentimentAnalysisServiceSettings.URL}?Code={sentimentAnalysisServiceSettings.Code}&text={text}"); 
            HttpResponseMessage response = await _client.SendAsync(sentimentRequest);

            var resultString = await response.Content.ReadAsStringAsync();
            return Convert.ToInt32(resultString);
            
        }

    }
}

Chapter06/azure/BookApp/BookApp.Web.V2/Controllers/BooksController.cs
using Microsoft.AspNetCore.Mvc;
using BookApp.DAL;
using BookApp.Models;

namespace BookApp.Web.V2.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository bookRepository;

        public BooksController(IBookRepository bookRepository)
        {
            this.bookRepository = bookRepository;
        }

        // GET: Books
        public ActionResult Index()
        {
            return View(bookRepository.GetBooks());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            Book book = bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Books/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind("Id,Title,SubTitle,DatePublished,CoverImage,Author")] Book book)
        {
            if (ModelState.IsValid)
            {
                bookRepository.UpsertBook(book);
                return RedirectToAction("Index");
            }

            return View(book);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            Book book = bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind("Id,Title,SubTitle,DatePublished,CoverImage,Author")] Book book)
        {
            if (ModelState.IsValid)
            {
                bookRepository.UpsertBook(book);

                return RedirectToAction("Index");
            }
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new BadRequestResult();
            }
            Book book = bookRepository.GetBookById(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bookRepository.DeleteBook(id);
            return RedirectToAction("Index");
        }
    }
}

Chapter06/azure/BookApp/BookApp.Web.V2/Views/Books/Details.cshtml
@model BookApp.Models.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatePublished)
        </dt>

        <dd>
            Date Published
        </dd>

        <dt>
            Cover Image
        </dt>

        <dd>
            @if (Model.CoverImage != null)
            {
                <img src="data:image;base64,@System.Convert.ToBase64String(Model.CoverImage)" style=" max-width: 150px;" />
            }

        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Reviews", "Index", "BookReviews", new { id = Model.Id }, null) |
    @Html.ActionLink("Back to List", "Index")
</p>

Chapter06/azure/BookApp/BookApp.Web.V2/Views/Books/Edit.cshtml
@model BookApp.Models.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Book</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatePublished, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatePublished, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatePublished, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CoverImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CoverImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CoverImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

}

Chapter06/azure/BookApp/BookApp.Web.V2/Views/Books/Index.cshtml
@model IEnumerable<BookApp.Models.Book>

@{
    ViewBag.Title = "Books List";
}

<h2>Books List</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubTitle)
        </th>
        <th>
            Date Published
        </th>
        <th>
            Cover Image
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SubTitle)
        </td>
        <td>
            @item.DatePublished.ToString("d")
        </td>
        <td>
            @if (item.CoverImage != null)
            {
                <img src="data:image;base64,@System.Convert.ToBase64String(item.CoverImage)" style=" max-width: 150px;" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Reviews", "Index", "BookReviews", new { id = item.Id },null) 
        </td>
    </tr>
}

</table>